/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/403': RouteRecordInfo<
      '/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples': RouteRecordInfo<
      '/examples',
      '/examples',
      Record<never, never>,
      Record<never, never>,
      | '/examples/content'
      | '/examples/content/excel'
      | '/examples/content/markdown'
      | '/examples/content/uploads'
      | '/examples/pages'
      | '/examples/pages/advanced-search'
      | '/examples/pages/batch-actions'
      | '/examples/pages/detail'
      | '/examples/pages/form'
      | '/examples/pages/inline-edit'
      | '/examples/pages/list'
      | '/examples/pages/tree-table'
      | '/examples/visual'
      | '/examples/visual/charts'
    >,
    '/examples/content': RouteRecordInfo<
      '/examples/content',
      '/examples/content',
      Record<never, never>,
      Record<never, never>,
      | '/examples/content/excel'
      | '/examples/content/markdown'
      | '/examples/content/uploads'
    >,
    '/examples/content/excel': RouteRecordInfo<
      '/examples/content/excel',
      '/examples/content/excel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/content/markdown': RouteRecordInfo<
      '/examples/content/markdown',
      '/examples/content/markdown',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/content/uploads': RouteRecordInfo<
      '/examples/content/uploads',
      '/examples/content/uploads',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages': RouteRecordInfo<
      '/examples/pages',
      '/examples/pages',
      Record<never, never>,
      Record<never, never>,
      | '/examples/pages/advanced-search'
      | '/examples/pages/batch-actions'
      | '/examples/pages/detail'
      | '/examples/pages/form'
      | '/examples/pages/inline-edit'
      | '/examples/pages/list'
      | '/examples/pages/tree-table'
    >,
    '/examples/pages/advanced-search': RouteRecordInfo<
      '/examples/pages/advanced-search',
      '/examples/pages/advanced-search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages/batch-actions': RouteRecordInfo<
      '/examples/pages/batch-actions',
      '/examples/pages/batch-actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages/detail': RouteRecordInfo<
      '/examples/pages/detail',
      '/examples/pages/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages/form': RouteRecordInfo<
      '/examples/pages/form',
      '/examples/pages/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages/inline-edit': RouteRecordInfo<
      '/examples/pages/inline-edit',
      '/examples/pages/inline-edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages/list': RouteRecordInfo<
      '/examples/pages/list',
      '/examples/pages/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/pages/tree-table': RouteRecordInfo<
      '/examples/pages/tree-table',
      '/examples/pages/tree-table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/examples/visual': RouteRecordInfo<
      '/examples/visual',
      '/examples/visual',
      Record<never, never>,
      Record<never, never>,
      | '/examples/visual/charts'
    >,
    '/examples/visual/charts': RouteRecordInfo<
      '/examples/visual/charts',
      '/examples/visual/charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile': RouteRecordInfo<
      '/profile',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system': RouteRecordInfo<
      '/system',
      '/system',
      Record<never, never>,
      Record<never, never>,
      | '/system/access'
      | '/system/access/roles'
      | '/system/access/users'
      | '/system/config'
      | '/system/config/dicts'
      | '/system/config/logs'
      | '/system/config/menus'
    >,
    '/system/access': RouteRecordInfo<
      '/system/access',
      '/system/access',
      Record<never, never>,
      Record<never, never>,
      | '/system/access/roles'
      | '/system/access/users'
    >,
    '/system/access/roles': RouteRecordInfo<
      '/system/access/roles',
      '/system/access/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/access/users': RouteRecordInfo<
      '/system/access/users',
      '/system/access/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/config': RouteRecordInfo<
      '/system/config',
      '/system/config',
      Record<never, never>,
      Record<never, never>,
      | '/system/config/dicts'
      | '/system/config/logs'
      | '/system/config/menus'
    >,
    '/system/config/dicts': RouteRecordInfo<
      '/system/config/dicts',
      '/system/config/dicts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/config/logs': RouteRecordInfo<
      '/system/config/logs',
      '/system/config/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/config/menus': RouteRecordInfo<
      '/system/config/menus',
      '/system/config/menus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/403.vue': {
      routes:
        | '/403'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/examples.vue': {
      routes:
        | '/examples'
        | '/examples/content'
        | '/examples/content/excel'
        | '/examples/content/markdown'
        | '/examples/content/uploads'
        | '/examples/pages'
        | '/examples/pages/advanced-search'
        | '/examples/pages/batch-actions'
        | '/examples/pages/detail'
        | '/examples/pages/form'
        | '/examples/pages/inline-edit'
        | '/examples/pages/list'
        | '/examples/pages/tree-table'
        | '/examples/visual'
        | '/examples/visual/charts'
      views:
        | 'default'
    }
    'src/pages/examples/content.vue': {
      routes:
        | '/examples/content'
        | '/examples/content/excel'
        | '/examples/content/markdown'
        | '/examples/content/uploads'
      views:
        | 'default'
    }
    'src/pages/examples/content/excel.vue': {
      routes:
        | '/examples/content/excel'
      views:
        | never
    }
    'src/pages/examples/content/markdown.vue': {
      routes:
        | '/examples/content/markdown'
      views:
        | never
    }
    'src/pages/examples/content/uploads.vue': {
      routes:
        | '/examples/content/uploads'
      views:
        | never
    }
    'src/pages/examples/pages.vue': {
      routes:
        | '/examples/pages'
        | '/examples/pages/advanced-search'
        | '/examples/pages/batch-actions'
        | '/examples/pages/detail'
        | '/examples/pages/form'
        | '/examples/pages/inline-edit'
        | '/examples/pages/list'
        | '/examples/pages/tree-table'
      views:
        | 'default'
    }
    'src/pages/examples/pages/advanced-search.vue': {
      routes:
        | '/examples/pages/advanced-search'
      views:
        | never
    }
    'src/pages/examples/pages/batch-actions.vue': {
      routes:
        | '/examples/pages/batch-actions'
      views:
        | never
    }
    'src/pages/examples/pages/detail.vue': {
      routes:
        | '/examples/pages/detail'
      views:
        | never
    }
    'src/pages/examples/pages/form.vue': {
      routes:
        | '/examples/pages/form'
      views:
        | never
    }
    'src/pages/examples/pages/inline-edit.vue': {
      routes:
        | '/examples/pages/inline-edit'
      views:
        | never
    }
    'src/pages/examples/pages/list.vue': {
      routes:
        | '/examples/pages/list'
      views:
        | never
    }
    'src/pages/examples/pages/tree-table.vue': {
      routes:
        | '/examples/pages/tree-table'
      views:
        | never
    }
    'src/pages/examples/visual.vue': {
      routes:
        | '/examples/visual'
        | '/examples/visual/charts'
      views:
        | 'default'
    }
    'src/pages/examples/visual/charts.vue': {
      routes:
        | '/examples/visual/charts'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/profile.vue': {
      routes:
        | '/profile'
      views:
        | never
    }
    'src/pages/system.vue': {
      routes:
        | '/system'
        | '/system/access'
        | '/system/access/roles'
        | '/system/access/users'
        | '/system/config'
        | '/system/config/dicts'
        | '/system/config/logs'
        | '/system/config/menus'
      views:
        | 'default'
    }
    'src/pages/system/access.vue': {
      routes:
        | '/system/access'
        | '/system/access/roles'
        | '/system/access/users'
      views:
        | 'default'
    }
    'src/pages/system/access/roles.vue': {
      routes:
        | '/system/access/roles'
      views:
        | never
    }
    'src/pages/system/access/users.vue': {
      routes:
        | '/system/access/users'
      views:
        | never
    }
    'src/pages/system/config.vue': {
      routes:
        | '/system/config'
        | '/system/config/dicts'
        | '/system/config/logs'
        | '/system/config/menus'
      views:
        | 'default'
    }
    'src/pages/system/config/dicts.vue': {
      routes:
        | '/system/config/dicts'
      views:
        | never
    }
    'src/pages/system/config/logs.vue': {
      routes:
        | '/system/config/logs'
      views:
        | never
    }
    'src/pages/system/config/menus.vue': {
      routes:
        | '/system/config/menus'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
