/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./layouts/AdminLayout.vue')['default']
    AppHeader: typeof import('./layouts/AppHeader.vue')['default']
    AppMain: typeof import('./layouts/AppMain.vue')['default']
    AppSidebar: typeof import('./layouts/AppSidebar.vue')['default']
    AppSidebarItem: typeof import('./layouts/AppSidebarItem.vue')['default']
    AppTabs: typeof import('./layouts/AppTabs.vue')['default']
    BlankLayout: typeof import('./layouts/BlankLayout.vue')['default']
    ChartContainer: typeof import('./components/admin/ChartContainer.vue')['default']
    ChartRenderer: typeof import('./components/admin/ChartRenderer.vue')['default']
    DataTable: typeof import('./components/admin/DataTable.vue')['default']
    DataToolbar: typeof import('./components/admin/DataToolbar.vue')['default']
    DetailSection: typeof import('./components/admin/DetailSection.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MarkdownEditorField: typeof import('./components/admin/MarkdownEditorField.vue')['default']
    MarkdownEditorRenderer: typeof import('./components/admin/MarkdownEditorRenderer.vue')['default']
    PageContainer: typeof import('./components/admin/PageContainer.vue')['default']
    PageHeader: typeof import('./components/admin/PageHeader.vue')['default']
    PermissionButton: typeof import('./components/admin/PermissionButton.vue')['default']
    QueryPanel: typeof import('./components/admin/QueryPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
